name: Deploy Web to Preview Channel

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    paths:
      - 'apps/larpcalendar-web/**'

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install && yarn nx build larpcalendar-web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LARP_CALENDAR_9F83F }}'
          expires: 30d
          projectId: larp-calendar-9f83f
