name: Deploy Web App to Live Channel

on:
  push:
    branches:
      - main
    paths:
      - 'apps/larpcalendar-web/**'

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install && yarn nx build larpcalendar-web
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LARP_CALENDAR }}'
          projectId: larp-calendar-9f83f
          channelId: live
