name: Deploy Web to Live Channel

on:
  push:
    branches:
      - main
    paths:
      - 'apps/larpcalendar-web/**'

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install && yarn nx build larpcalendar-web
        env:
          NX_FIREBASE_API_KEY: '${{ secrets.NX_FIREBASE_API_KEY }}'
          NX_FIREBASE_AUTH_DOMAIN: '${{ secrets.NX_FIREBASE_AUTH_DOMAIN }}'
          NX_FIREBASE_PROJECT_ID: '${{ secrets.NX_FIREBASE_PROJECT_ID }}'
          NX_FIREBASE_STORAGE_BUCKET: '${{ secrets.NX_FIREBASE_STORAGE_BUCKET }}'
          NX_FIREBASE_MESSAGING_SENDER_ID: '${{ secrets.NX_FIREBASE_MESSAGING_SENDER_ID }}'
          NX_FIREBASE_APP_ID: '${{ secrets.NX_FIREBASE_APP_ID }}'
          NX_FIREBASE_MEASUREMENT_ID: '${{ secrets.NX_FIREBASE_MEASUREMENT_ID }}'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_LARP_CALENDAR_9F83F }}'
          projectId: '${{ secrets.NX_FIREBASE_PROJECT_ID }}'
          channelId: live
